name: Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3
    - name: Install python3-setuptools
      run: pip3 install --upgrade setuptools
    - name: Build egg
      run: python3 setup.py bdist_egg
